import dotenv from 'dotenv'

dotenv.config({path: './.env'})

export const STACKS_API_URL = process.env.STACKS_API_URL
export const MODE = process.env.MODE

export const CONTRACT_NAME_SIP010_TRAIT = process.env.CONTRACT_NAME_SIP010_TRAIT
export const CONTRACT_NAME_LIQUIDITY_TOKEN_TRAIT = process.env.CONTRACT_NAME_LIQUIDITY_TOKEN_TRAIT
export const CONTRACT_NAME_RESTRICTED_TOKEN_TRAIT = process.env.CONTRACT_NAME_RESTRICTED_TOKEN_TRAIT
export const CONTRACT_NAME_STACKSWAP_DAO_TOKEN_TRAIT = process.env.CONTRACT_NAME_STACKSWAP_DAO_TOKEN_TRAIT
export const CONTRACT_NAME_INITIALIZABLE_TOKEN_TRAIT = process.env.CONTRACT_NAME_INITIALIZABLE_TOKEN_TRAIT


export const CONTRACT_NAME_STACKSWAP_SWAP_V1 = process.env.CONTRACT_NAME_STACKSWAP_SWAP_V1
export const CONTRACT_NAME_STACKSWAP_SWAP_FEE_V1 = process.env.CONTRACT_NAME_STACKSWAP_SWAP_FEE_V1
export const CONTRACT_NAME_STACKSWAP_ONE_STEP_MINT_V1 = process.env.CONTRACT_NAME_STACKSWAP_ONE_STEP_MINT_V1
export const CONTRACT_NAME_STACKSWAP_ONE_STEP_MINT_FEE_V1 = process.env.CONTRACT_NAME_STACKSWAP_ONE_STEP_MINT_FEE_V1

export const CONTRACT_NAME_STACKSWAP_DAO = process.env.CONTRACT_NAME_STACKSWAP_DAO
export const CONTRACT_NAME_STACKSWAP_GOVERNANCE_V1 = process.env.CONTRACT_NAME_STACKSWAP_GOVERNANCE_V1

export const CONTRACT_NAME_STACKSWAP_FARMING = process.env.CONTRACT_NAME_STACKSWAP_FARMING
export const CONTRACT_NAME_STACKSWAP_FARMING_REWARD = process.env.CONTRACT_NAME_STACKSWAP_FARMING_REWARD

export const CONTRACT_NAME_VSTSW = process.env.CONTRACT_NAME_VSTSW
export const CONTRACT_NAME_STSW = process.env.CONTRACT_NAME_STSW
export const CONTRACT_NAME_WSTX = process.env.CONTRACT_NAME_WSTX
export const CONTRACT_NAME_PLAID = process.env.CONTRACT_NAME_PLAID
export const CONTRACT_NAME_PLAID_WSTX = process.env.CONTRACT_NAME_PLAID_WSTX
export const CONTRACT_NAME_TOKENSOFT = process.env.CONTRACT_NAME_TOKENSOFT
export const CONTRACT_NAME_TOKENSOFT_V2 = process.env.CONTRACT_NAME_TOKENSOFT_V2
export const CONTRACT_NAME_TOKENSOFT_WSTX = process.env.CONTRACT_NAME_TOKENSOFT_WSTX
export const CONTRACT_NAME_POXLSOFT_V1 = process.env.CONTRACT_NAME_POXLSOFT_V1
export const CONTRACT_NAME_LIQUIDITY_TOKENSOFT_V1 = process.env.CONTRACT_NAME_LIQUIDITY_TOKENSOFT_V1

export const STSW_PK = process.env.STSW_PK
export const STSW_SK = process.env.STSW_SK
export const STSW_STX = process.env.STSW_STX

export const USER1_STX = process.env.USER1_STX
export const USER1_SK = process.env.USER1_SK
export const USER1_PK = process.env.USER1_PK
export const USER2_STX = process.env.USER2_STX
export const USER2_SK = process.env.USER2_SK
export const USER2_PK = process.env.USER2_PK